/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifsp.pep.view;

import br.edu.ifsp.pep.dao.FrequenciaDAO;
import br.edu.ifsp.pep.dao.MatriculaDAO;
import br.edu.ifsp.pep.modelo.Frequencia;
import br.edu.ifsp.pep.modelo.Matricula;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author murilo
 */
public class LiberarAcessoView extends javax.swing.JFrame {

    private final MatriculaDAO matriculaDAO = new MatriculaDAO();
    private Matricula matricula = new Matricula();
    private Frequencia frequencia = new Frequencia();
    private final FrequenciaDAO frequenciaDAO = new FrequenciaDAO();
    private List<Matricula> matriculas;
    private List<Frequencia> frequencias;

    /**
     * Creates new form LiberarAcessoView
     */
    public LiberarAcessoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pLogin = new javax.swing.JPanel();
        lTitulo = new javax.swing.JLabel();
        lMatricula = new javax.swing.JLabel();
        tfMatricula = new javax.swing.JTextField();
        bEntrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pLogin.setBackground(new java.awt.Color(255, 255, 255));

        lTitulo.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        lTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lTitulo.setText("LIBERAR ACESSO");

        lMatricula.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lMatricula.setText("Matricula:");

        tfMatricula.setBackground(new java.awt.Color(204, 204, 204));
        tfMatricula.setFont(new java.awt.Font("Liberation Sans", 0, 17)); // NOI18N

        bEntrar.setBackground(new java.awt.Color(0, 153, 255));
        bEntrar.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        bEntrar.setText("Entrar");
        bEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pLoginLayout = new javax.swing.GroupLayout(pLogin);
        pLogin.setLayout(pLoginLayout);
        pLoginLayout.setHorizontalGroup(
            pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoginLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lMatricula)
                    .addComponent(tfMatricula)
                    .addComponent(bEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addContainerGap())
        );
        pLoginLayout.setVerticalGroup(
            pLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pLoginLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(lTitulo)
                .addGap(40, 40, 40)
                .addComponent(lMatricula)
                .addGap(18, 18, 18)
                .addComponent(tfMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(bEntrar)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 631, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEntrarActionPerformed
        if (tfMatricula.getText().length() > 0) {
            if (tfMatricula.getText().matches("^\\d+$")) {
                int matriculaAluno = Integer.parseInt(tfMatricula.getText());
                matriculas = matriculaDAO.findByMatricula(matriculaAluno);
                if (!matriculas.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Acesso Liberado!", "Sucesso!", JOptionPane.INFORMATION_MESSAGE);
                    matricula = matriculas.get(0);
                    if (!verificarFrequencia()) {
                        try {
                            frequencia = new Frequencia(new Date(), matricula.getAluno());
                            frequenciaDAO.inserir(frequencia);
                        } catch (Exception ex) {
                            Logger.getLogger(LiberarAcessoView.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Matrícula Inválida!", "Atenção", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Digite apenas números para a matrícula!", "Atenção", JOptionPane.WARNING_MESSAGE);

            }

        } else {
            JOptionPane.showMessageDialog(null, "Digite a matrícula para liberar o acesso!", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bEntrarActionPerformed

    private boolean verificarFrequencia() {
        frequencias = frequenciaDAO.findByCpf(matricula.getAluno().getCpf());
        boolean contemData = false;
        SimpleDateFormat formatarData = new SimpleDateFormat("dd/MM/yyyy");
        String hoje = formatarData.format(new Date());
        String frequenciaData;
        for (Frequencia frequencia1 : frequencias) {
            frequenciaData = formatarData.format(frequencia1.getData());
            if (frequenciaData.equals(hoje)) {
                contemData = true;
            }
        }
        return contemData;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LiberarAcessoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LiberarAcessoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LiberarAcessoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LiberarAcessoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LiberarAcessoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEntrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lMatricula;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JPanel pLogin;
    private javax.swing.JTextField tfMatricula;
    // End of variables declaration//GEN-END:variables
}
